### ISSUE TITLE
Should we modify requests through :>?

### ISSUE THREAD

**Issue by soenkehahn** [alpmestan/servant#7]
``` haskell
type Api =
       "path" :> Raw
  :<|> GetParam "param" String :> Raw
  :<|> GetParam "foo" :> GetParam "foo" :> Get ()
```

In this example -- when implementing a server -- should the `Application`s that implement both `Raw` endpoints be handed a modified request? So should the first one get a request where `"path"` is stripped from `pathInfo` and the second one a request where `"param"` is deleted from `queryString`? Or should they always get an unmodified request?

Similarly, should the third route (with `Get ()`) work? Or should the second `GetParam "foo"` always fail, since the first one removes `"foo"` from `queryString`?

cc: @alpmestan @jkarni

**Comment by alpmestan** [comment]
Ok, here are my answers (to be compared to what you guys think should happen):

1/ Yes, and I think this behavior actually makes our "actions" local, so that they can be nested in others and get moved around, they may actually work everywhere without any problem, as long as the function you provide to implement it takes the appropriate arguments (for captures, get params, rq body). Except that I don't delete GET parameters from the query string when reading them. I just look them up -- since there always is a query string, and it doesn't mutate during one request.

2/ Like I said, nothing is removed from the query string right now, so it'll work. You'll just have twice the same value for the 2 arguments to the endpoint.

Do we want instances for `()` btw, so that when we want an empty object/array/document as a response, we can just use that?

**Comment by jkarni** [comment]
I largely agree. I feel pretty strongly that "path" ought to be stripped - it allows for a much more modular design. As for the query string, I'm not sure. If we follow Postel's law, nothing should fail because of extra params, and so it would seem that keeping the params shouldn't matter. On the other hand, there is a little bit of ambiguity when two parts of a path want to use the same param: is it really the same param (in which case they should be allowed to), or is it a different param that just happens to have the same name (which could accidentally happen in a modularly-designed, large service)?

So on (2), I don't think I know enough about how things will pan out, and am happy to go with whichever is most convenient for now.

**Comment by soenkehahn** [comment]
Ok, so we modify the `pathInfo`, but leave everything else unmodified.

**Comment by soenkehahn** [comment]
Implemented through https://github.com/zalora/servant/commit/617843b8f832e22a9fefd999c03bb05d8e87d0a8.

**Comment by alpmestan** [comment]
Does that close this issue?

**Comment by soenkehahn** [comment]
Yep, just waited for the merge.
